name       : sdl1
version    : 1.2.15
release    : 9
source     :
    - http://www.libsdl.org/release/SDL-1.2.15.tar.gz : d6d316a793e5e348155f0dd93b979798933fb98aa1edebcc108829d6474aad00
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : Simple DirectMedia Layer 1.x
description: |
    Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D. It is used by video playback software, emulators, and popular games including Valve's award winning catalog and many Humble Bundle games.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(glu)
    - pkgconfig32(libpulse)
    - pkgconfig32(libusb-1.0)
    - pkgconfig32(xrandr)
    - pkgconfig32(zlib)
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/SDL-1.2.15-const_XData32.patch
    %configure --disable-static \
               --enable-shared \
               --with-x \
               --enable-alsa \
               --enable-pulseaudio \
               --enable-pulseaudio-shared \
               --enable-sse2 \
               --enable-ssemath \
               --disable-rpath
build      : |
    %make
install    : |
    %make_install
